### ISSUE TITLE
TCLI broken for all mods/modpacks.  JSON integer 3909573219 is too large or small for an Int32

### ISSUE THREAD

**Issue by smorehouse** [thunderstore-io/thunderstore-cli#103]
Full stack: 
`~/tcli/tcli-0.2.3-linux-x64$ ./tcli install --profile 2024-06-05 valheim NOI_or_Die-NOI_or_Die-2.0.5

Downloading main package: NOI_or_Die-NOI_or_Die

Unhandled exception. Newtonsoft.Json.JsonReaderException: JSON integer 3909573219 is too large or small for an Int32. Path '[59].versions[0].file_size', line 1, position 2921397.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ThunderstoreCLI.Utils.ModDependencyTree.Generate(Config config, HttpClient http, PackageManifestV1 root, String sourceCommunity, Boolean useExactVersions)
   at ThunderstoreCLI.Commands.InstallCommand.InstallZip(Config config, HttpClient http, GameDefinition game, ModProfile profile, String zipPath, String backupNamespace, String sourceCommunity, Boolean isModpack)
   at ThunderstoreCLI.Commands.InstallCommand.InstallFromRepository(Config config, HttpClient http, GameDefinition game, ModProfile profile, Match packageMatch)
   at ThunderstoreCLI.Commands.InstallCommand.Run(Config config)
   at ThunderstoreCLI.ModManagementOptions.Execute()
   at ThunderstoreCLI.Program.HandleParsed(BaseOptions parsed)
   at ThunderstoreCLI.Program.Main(String[] args)
Aborted (core dumped)`

**Comment by smorehouse** [comment]
I figured out the problem. In the json returned by https://thunderstore.io/c/valheim/api/v1/package/ there is a mod https://thunderstore.io/c/valheim/p/Belze/Valyrim_Music/ that is 3.9gb and the file_size is larger than int32 can handle. Deleting this mod will fix tcli.

**Comment by MythicManiac** [comment]
Thanks for the report

**Comment by Digitalroot** [comment]
This is the current offender. 
```json
{
  "name": "Valyrim",
  "full_name": "Belze-Valyrim-1.0.1",
  "description": "This mod changes MOST of the in-game sounds into Skyrim ones. Some sounds, background music and menu sounds have been replaced. NOTE: Some sounds come from Morrowind and Oblivion due personal choice. Hope you don't mind! :) Logo made with AI.",
  "icon": "https://gcdn.thunderstore.io/live/repository/icons/Belze-Valyrim-1.0.1.png",
  "version_number": "1.0.1",
  "dependencies": [
    "denikson-BepInExPack_Valheim-5.4.2202",
    "TRGC-aedenthornCustomAudio-1.5.1"
  ],
  "download_url": "https://thunderstore.io/package/download/Belze/Valyrim/1.0.1/",
  "downloads": 14,
  "date_created": "2024-06-04T14:07:30.783364Z",
  "website_url": "https://thunderstore.io/c/valheim/p/Belze/",
  "is_active": true,
  "uuid4": "ea44aaef-7285-4851-af1b-71a7eda2ef4b",
  "file_size": 4133258204
},
```

```
Unhandled exception. Newtonsoft.Json.JsonReaderException: JSON integer 4133258204 is too large or small for an Int32. Path '[47].versions[3].file_size', line 1, position 2450232.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
```

**Comment by MythicManiac** [comment]
The [0.2.4 release](https://github.com/thunderstore-io/thunderstore-cli/releases/tag/0.2.4) should have this fixed now, let me know if you still run into the issue

**Comment by smorehouse** [comment]
I can test in a couple of hours thanks @MythicManiac !!

**Comment by smorehouse** [comment]
@MythicManiac tested 0.2.4 and it works like a charm!! Thanks for the quick fix!!!!
